apiVersion: v1
kind: Secret
metadata:
  name: magazyn360-secrets
type: Opaque
stringData:
  POSTGRES_DB: "{{ .Values.secrets.POSTGRES_DB }}"
  POSTGRES_USER: "{{ .Values.secrets.POSTGRES_USER }}"
  POSTGRES_PASSWORD: "{{ .Values.secrets.POSTGRES_PASSWORD }}"
  POSTGRES_HOST: "{{ .Values.secrets.POSTGRES_HOST }}"
  POSTGRES_PORT: "{{ .Values.secrets.POSTGRES_PORT }}"
  SECRET_KEY: "{{ .Values.secrets.SECRET_KEY }}"
  JWT_ACCESS_TOKEN_LIFETIME_MINUTES: "{{ .Values.secrets.JWT_ACCESS_TOKEN_LIFETIME_MINUTES }}"
  JWT_REFRESH_TOKEN_LIFETIME_DAYS: "{{ .Values.secrets.JWT_REFRESH_TOKEN_LIFETIME_DAYS }}"
  JWT_ROTATE_REFRESH_TOKENS: "{{ .Values.secrets.JWT_ROTATE_REFRESH_TOKENS }}"
  JWT_BLACKLIST_AFTER_ROTATION: "{{ .Values.secrets.JWT_BLACKLIST_AFTER_ROTATION }}"
