# Generated by Django 5.2 on 2025-05-11 09:57

import apps.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="name",
            field=models.CharField(
                help_text="Identifier for the address",
                max_length=255,
                verbose_name="Address Name",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="type",
            field=models.CharField(
                choices=[
                    ("office", "Office"),
                    ("billing", "Billing"),
                    ("shipping", "Shipping"),
                    ("warehouse", "Warehouse"),
                    ("factory", "Factory"),
                    ("head_office", "Head Office"),
                    ("other", "Other"),
                ],
                default="billing",
                help_text="Type of address (billing, shipping, etc.)",
                max_length=50,
                verbose_name="Address Type",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="email",
            field=models.EmailField(
                help_text="Company email",
                max_length=254,
                unique=True,
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="national_court_register",
            field=models.CharField(
                help_text="National Court Register 10 digits",
                max_length=20,
                validators=[apps.core.validators.KRSValidator()],
                verbose_name="National Court Register (KRS)",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="owner",
            field=models.ForeignKey(
                help_text="Company owner",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owned_companies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="phone",
            field=models.CharField(
                help_text="Company phone number",
                max_length=20,
                validators=[apps.core.validators.PolishPhoneNumberValidator()],
                verbose_name="Phone Number",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="statistical_number",
            field=models.CharField(
                help_text="Statistical Number 9 or 14 digits",
                max_length=20,
                validators=[apps.core.validators.REGONValidator()],
                verbose_name="Statistical Number (REGON)",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="tax_id",
            field=models.CharField(
                help_text="Tax Identification Number 10 digits",
                max_length=20,
                validators=[apps.core.validators.NIPValidator()],
                verbose_name="Tax ID (NIP)",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="website",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Company website",
                verbose_name="Website",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated company",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="core.company",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="department",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Department"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Email address"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Optional Polish phone number",
                max_length=20,
                validators=[apps.core.validators.PolishPhoneNumberValidator()],
                verbose_name="Phone Number",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="position",
            field=models.CharField(
                blank=True,
                help_text="Job position",
                max_length=50,
                verbose_name="Position",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("viewer", "Viewer"),
                    ("worker", "Worker"),
                    ("manager", "Manager"),
                    ("admin", "Admin"),
                    ("owner", "Owner"),
                ],
                default="viewer",
                help_text="User role in the system",
                verbose_name="Role",
            ),
        ),
    ]
