# Generated by Django 5.2.1 on 2025-08-18 20:19

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_alter_address_name_alter_address_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("sku", models.CharField(max_length=64)),
                (
                    "ean",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=13
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("szt", "Sztuka"),
                            ("kg", "Kilogram"),
                            ("m3", "Metr sześcienny"),
                            ("m", "Metr"),
                        ],
                        default="szt",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "min_stock",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "max_stock",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="core.company",
                        verbose_name="Company",
                    ),
                ),
            ],
            options={
                "ordering": ["company_id", "name"],
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="warehouses",
                        to="core.address",
                        verbose_name="Address",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouses",
                        to="core.company",
                        verbose_name="Company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Warehouse",
                "verbose_name_plural": "Warehouses",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "reserved",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="warehouse.product",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="warehouse.warehouse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WarehouseDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("PZ", "Przyjęcie zewnętrzne"),
                            ("WZ", "Wydanie zewnętrzne"),
                            ("MM", "Przesunięcie międzymagazynowe"),
                            ("RW", "Rozchód wewnętrzny"),
                            ("PW", "Przyjęcie wewnętrzne"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Wersja robocza"),
                            ("posted", "Zaksięgowany"),
                            ("cancelled", "Anulowany"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("number", models.CharField(max_length=64)),
                ("date", models.DateField(db_index=True)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fiscal_year", models.PositiveIntegerField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="warehouse_documents",
                        to="core.company",
                    ),
                ),
                (
                    "from_warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_transfers",
                        to="warehouse.warehouse",
                    ),
                ),
                (
                    "to_warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_transfers",
                        to="warehouse.warehouse",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="warehouse.warehouse",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WarehouseDocumentItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=16)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("szt", "Sztuka"),
                            ("kg", "Kilogram"),
                            ("m3", "Metr sześcienny"),
                            ("m", "Metr"),
                        ],
                        default="szt",
                        max_length=16,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="warehouse.warehousedocument",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.product",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["company", "name"], name="warehouse_p_company_7673f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["company", "sku"], name="warehouse_p_company_3512ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active"], name="warehouse_p_is_acti_f643f3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("company", "sku"), name="uniq_product_sku_per_company"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("min_stock__gte", 0)),
                name="product_min_stock_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_stock__gte", 0)),
                name="product_max_stock_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="warehouse",
            index=models.Index(
                fields=["company", "name"], name="warehouse_w_company_ca4ef9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="warehouse",
            index=models.Index(
                fields=["is_active"], name="warehouse_w_is_acti_5ddb4a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(
                fields=["warehouse", "product"], name="warehouse_s_warehou_738a7b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="stock",
            constraint=models.UniqueConstraint(
                fields=("warehouse", "product"), name="uniq_stock_per_warehouse_product"
            ),
        ),
        migrations.AddConstraint(
            model_name="stock",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 0)),
                name="stock_quantity_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="stock",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved__gte", 0)),
                name="stock_reserved_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="warehousedocument",
            index=models.Index(
                fields=["company", "doc_type", "date"],
                name="warehouse_w_company_e291bd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="warehousedocument",
            index=models.Index(fields=["status"], name="warehouse_w_status_e703d5_idx"),
        ),
        migrations.AddConstraint(
            model_name="warehousedocument",
            constraint=models.UniqueConstraint(
                fields=("company", "doc_type", "fiscal_year", "number"),
                name="uniq_document_number_per_company_type_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="warehousedocument",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("doc_type", "MM"),
                        ("from_warehouse__isnull", False),
                        ("to_warehouse__isnull", False),
                    ),
                    models.Q(("doc_type", "MM"), _negated=True),
                    _connector="OR",
                ),
                name="doc_mm_requires_from_and_to",
            ),
        ),
        migrations.AddConstraint(
            model_name="warehousedocument",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("doc_type", "MM"),
                        ("from_warehouse__isnull", False),
                        models.Q(
                            ("from_warehouse", models.F("to_warehouse")), _negated=True
                        ),
                    ),
                    models.Q(("doc_type", "MM"), _negated=True),
                    _connector="OR",
                ),
                name="doc_mm_from_to_must_differ",
            ),
        ),
        migrations.AddIndex(
            model_name="warehousedocumentitem",
            index=models.Index(
                fields=["document"], name="warehouse_w_documen_3cc3c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="warehousedocumentitem",
            index=models.Index(
                fields=["product"], name="warehouse_w_product_e28983_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="warehousedocumentitem",
            constraint=models.UniqueConstraint(
                fields=("document", "product"), name="uniq_item_per_document_product"
            ),
        ),
        migrations.AddConstraint(
            model_name="warehousedocumentitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="doc_item_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="warehousedocumentitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("price__isnull", True), ("price__gte", 0), _connector="OR"
                ),
                name="doc_item_price_non_negative",
            ),
        ),
    ]
