# Generated by Django 5.2.5 on 2025-09-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0003_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True, default="", help_text="Product description", max_length=2000
            ),
        ),
    ]
