image:
  repository: ghcr.io/aleksanderbialka/magazyn360
  tag: dev
  pullPolicy: IfNotPresent
  pullSecrets:
    - ghcr-auth

replicaCount: 1

service:
  type: ClusterIP
  port: 8000

postgres:
  host: magazyn360-postgres
  port: 5432
  user: test
  db: local

django:
  allowedHosts: localhost,127.0.0.1,magazyn360.local,magazyn360.k8s,magazyn360.pl,magazyn360.magazyn360.svc.cluster.local,www.magazyn360.pl
  debug: "False"

ingress:
  enabled: true
  host: magazyn360.pl
