# ######################## formatting and linting tools ########################
[tool.pycln]
all = true

[tool.vulture]
make_whitelist = true
min_confidence = 80
paths = ["apps", "magazyn360"]
sort_by_size = true
exclude = ["migrations", "static", "media", "tests", "venv"]

[tool.mypy]
plugins = ["pydantic.mypy"]
python_version = "3.13"
check_untyped_defs = true
allow_redefinition = false
disallow_any_generics = true
disallow_any_explicit = false
disallow_untyped_calls = true
disallow_untyped_decorators = true
ignore_errors = false
ignore_missing_imports = true
implicit_reexport = false
no_implicit_optional = true
strict_optional = true
strict_equality = true
local_partial_types = true
warn_no_return = true
warn_unreachable = true
warn_unused_ignores = true
warn_unused_configs = true
warn_redundant_casts = true

[[tool.mypy.overrides]]
module = ["tests"]
ignore_errors = true
implicit_reexport = true

# ######################## basic poetry configuration ########################
[tool.poetry]
name = "magazyn360-api"
version = "0.1.0"
description = ""
authors = ["aleksanderbialka <aleksander.bialka@icloud.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"
django = "^5.2"
djangorestframework = "^3.16.0"
djangorestframework-simplejwt = "^5.5.0"
psycopg2-binary = "^2.9.10"
django-environ = "^0.12.0"
django-cors-headers = "^4.7.0"
drf-yasg = "^1.21.10"
sentry-sdk = "^2.25.1"
sphinx = "^8.2.3"
sphinx-rtd-theme = "^3.0.2"
sphinxcontrib-django = "^2.5"
gunicorn = "^23.0.0"
whitenoise = "^6.9.0"
django-filter = "^25.1"
kafka-python = "^2.2.15"


[tool.poetry.group.dev.dependencies]
ruff = "^0.12.0"
black = "^25.1.0"
pre-commit = "^4.2.0"
mypy = "^1.16.1"
vulture = "^2.14"

[tool.poetry.group.pytest.dependencies]
pytest-django = "^4.11.1"
pytest-asyncio = "^0.26.0"
coverage = "^7.8.0"
pytest-cov = "^6.1.1"
pytest-mock = "^3.14.0"
pytest-github-actions-annotate-failures = "^0.3.0"
pytest-html = "^4.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

# ######################## pytest configuration ########################
[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "magazyn360.settings"
python_files = "tests.py test_*.py *_tests.py"
python_functions = "test_*"
addopts = "--cov=apps --cov-report=html --cov-report=term-missing"

# ################ ################ ruff configuration #################
[tool.ruff]
extend-exclude = ["__pycache__", "*/migrations/*"]
force-exclude = true
namespace-packages = ["apps", "magazyn360"]
required-version = ">=0.12.0"
target-version = "py313"

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 72

[tool.ruff.lint]
extend-select = [
    "E5",  # pep8 (`E5`)
    "W",  # Warning (`W`)
    "C90",  # mccabe (`C90`)
    "I",  # isort (`I`)
    "N",  # pep8-naming (`N`)
    "UP",  # pyupgrade (`UP`) - eg. UP032: Use f-string instead of format call
    "S",  # flake8-bandit (`S`)
    "BLE",  # flake8-blind-except (`BLE`)
    "B",  # flake8-bugbear (`B`)
    "A",  # flake8-builtins (`A`)
    "COM",  # flake8-commas (`COM`)
    "C4",  # flake8-comprehensions (`C4`)
    "DJ",  # flake8-django (`DJ`)
    "LOG",  # flake8-logging (`LOG`)
    "G",  # flake8-logging-format (`G`) - logging.info("Something happened: %s", var)
    "T20",  # flake8-print (`T20`)
    "PT",  # flake8-pytest-style (`PT`)
    "RUF",
]

ignore = ["E741", "S4", "COM812", "RUF012", "RUF001"]

[tool.ruff.lint.per-file-ignores]
"test_*.py" = ["S101"]

[tool.ruff.lint.flake8-bandit]
check-typed-exception = true

[tool.ruff.lint.isort]
lines-after-imports = 2
order-by-type = false

[tool.ruff.lint.mccabe]
max-complexity = 30

[tool.ruff.lint.pycodestyle]
ignore-overlong-task-comments = true
max-doc-length = 88
max-line-length = 100
